import { MAPS } from '../game/constants.js';
import { state } from '../game/state.js';

export function resetState() {
	localStorage.clear();

	Object.assign(state, {
		canvas: null,
		ctx: null,
		sceneEl: null,
		engineStarted: false,
		engineReady: true,
		width: 0,
		height: 0,
		img: null,
		mspacImg: null,
		mapPixels: null,
		mapOffX: 0,
		mapOffY: 0,
		mapScaledW: 0,
		mapScaledH: 0,
		mapIdx: 0,
		startingMapIdx: 0,
		activeMap: MAPS[0],
		playerSpriteSheet: MAPS[0].spriteSheet,
		GRID_COLS: 0,
		GRID_ROWS: 0,
		grid: null,
		dots: null,
		bigDots: null,
		dotsEaten: 0,
		fruitDotsSinceSpawn: 0,
		pacman: { init() {}, nextDir: -1, update() {}, draw() {}, col: 13, row: 23 },
		ghosts: [],
		scaredTimer: 0,
		ghostEatenFreezeTimer: 0,
		scatterPhase: 0,
		scatterTimer: 420,
		score: 0,
		lastExtraLifeScore: 0,
		highScore: 0,
		username: '',
		lives: 3,
		level: 1,
		ghostCombo: 0,
		stateTimer: 0,
		cherry: null,
		scorePopups: [],
		gameState: 'menu',
		paused: false,
		aiMode: false,
		menuSelected: 0,
		menuSubState: 'main',
		aiPersonalityIdx: 1,
		selectedGhostIdx: -1,
		controlledGhostIdx: -1,
		ghostIndicatorStyle: 0,
		indicatorStyleBounds: null,
		escapeMenuActive: false,
		escapeMenuSelected: 0,
		backConfirmActive: false,
		backConfirmSelected: 0,
		settingsOverlayActive: false,
		settingsRow: 0,
		personalityRow: 0,
		menuStartFrame: -1,
		audioCtx: null,
		audioBuffers: {},
		volume: 0.5,
		muted: false,
		gameSpeed: 1,
		pendingBeginning: false,
		activeLoopTrack: null,
		loopNodes: null,
		frames: 0,
		frame: 0,
		aiPath: [],
		showPaths: { pacman: false, blinky: false, pinky: false, inky: false, clyde: false },
		showInfoPanel: false,
		volTrackBounds: null,
		volIconBounds: null,
		draggingVolume: false,
		speedTrackBounds: null,
		speedIconBounds: null,
		draggingSpeed: false,
		settingToast: { text: '', timer: 0 },
	});
}
